config/routes.rb
Rails.application.routes.draw do
  get 'schedules/show'
  get 'profiles/show'
  get 'profiles/update'
  get 'pages/dashboard'
  devise_for :users
  root to: "pages#home"
  get "/dashboard", to: "pages#dashboard"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  resources :scans, only: [ :new, :create, :show ] do
    resources :recipes, only: [ :new, :create, :show ]
  end

  resources :recipes do
  collection do
    get :filters
  end
end

  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :recipes, only: [:index]
  resources :recipes do
    resources :reviews, only: [:create, :index]
    post :toggle_favorite, on: :member
    post :like, on: :member
  end
  resource :profile, only: [:show, :update]
  resources :schedules, only: [:index, :create] do
    collection do
      post :generate_ai
    end
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  validates :date, presence: true
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedule = current_user.schedules.new
    @schedules = current_user.schedules.includes(:recipe)
    @start_date = params[:start_date] ? Date.parse(params[:start_date]) : Date.today

    @recipes = if params[:query].present?
                current_user.favorites.where("name ILIKE ?", "%#{params[:query]}%")
              else
                current_user.favorites
              end
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def create
    @schedule = current_user.schedules.new(schedule_params)
    @recipes = current_user.recipes
    if @schedule.save
      @schedules = current_user.schedules.includes(:recipe)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to schedules_path(start_date: @schedule.date.beginning_of_month), status: :see_other }
      end
    else
      render :index, status: :unprocessable_content
    end
  end

  def generate_ai
    SchedulerbroadcastJob.perform_later(current_user.id, params.to_unsafe_h)

    respond_to do |format|
      format.turbo_stream # pode ter um spinner ou aviso "gerando receitas..."
      format.html { redirect_to schedules_path, notice: "Gerando receitas, isso pode levar alguns segundos..." }
    end
  end

  private

  def schedule_params
    params.require(:schedule).permit(:date, :recipe_id)
  end
end

app/views/schedules/_ai.html.erb
<%= simple_form_for schedule, url: generate_ai_schedules_path,
  data: { scheduler_target: "aiFormScheduler", controller: "form-ai" },
   method: :post do |f| %>
  <div id="customDateField" class="my-3">
    <label for="start_date">Start Date</label>
    <%= date_field_tag :start_date, nil,
    class: "form-control",
    data: { controller: "datepicker"},
    placeholder: "Pick a date" %>
  </div>
  <div class="btn-group mb-3 w-100" id="divPeriod" role="group" aria-label="Basic radio toggle button group">
    <input type="radio"
      value="7"
      class="btn-check" name="btnradio"
      id="btnDays" autocomplete="off"
      data-action="click->form-ai#periodClick" checked>
    <label class="btn btn-outline-cSeaGreen" for="btnDays">7 Days</label>
    <input type="radio" class="btn-check"
      name="btnradio" id="btnMonth"
      value="30"
      autocomplete="off"
      data-action="click->form-ai#periodClick">
    <label class="btn btn-outline-cSeaGreen" for="btnMonth">30 Days</label>
    <input type="radio" class="btn-check"
      name="btnradio"
      value="other"
      id="btnOther"
      autocomplete="off"
      data-action="click->form-ai#periodClick">
    <label class="btn btn-outline-cSeaGreen" for="btnOther">Other</label>
  </div>
  <div class="mb-3 d-none" data-form-ai-target="customPeriodInput">
    <%= number_field_tag :custom_period, nil,
          class: "form-control",
          placeholder: "Enter number of days",
          data: { action: "input->selectable#updateCustom" } %>
  </div>
  <%= hidden_field_tag :period, "", data: { form_ai_target: "hiddenPeriod" } %>
  <%= f.submit "Generate AI Schedule", class: "btn btn-cYellow w-100" %>
<% end %>

app/views/schedules/_calendar.html.erb
<div>
  <%= month_calendar events: schedules, attribute: :date, url: schedules_path do |date, schedules_day| %>
    <div class="day calendar-day position-relative" data-action="click->scheduler#calendarEvent">
      <%= date.day %>
      <% if schedules_day.count > 0 %>
        <span class="badge text-bg-cYellow rounded-circle position-absolute calendar-badge" style="top: 3px; right: 0;">
          <%= schedules_day.count %>
        </span>
      <% end %>
      <div class="calendar-event">
        <% schedules_day.each do |schedule| %>
          <div data-recipe="<%= recipe_path(schedule.recipe) %>" data-name="<%= schedule.recipe.name %>"></div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/schedules/_form.html.erb
<%= simple_form_for schedule, data: { scheduler_target: "formScheduler" } do |f| %>
  <%= f.input :date, as: :string, input_html: { class: "form-control", data: { controller: "datepicker" } } %>
  <div data-scheduler-url-value="<%= schedules_path %>">
    <%= text_field_tag :query,
          params[:query],
          class: "fd-search-input fd-pill",
          placeholder: "Find a recipe...",
          data: { action: 'input->scheduler#submit', scheduler_target: "searchinput" } %>
    <div id="schedulerrecipe" class="row p-1">
      <%= render "schedules/search", recipes: current_user.favorited_by_type('Recipe') %>
    </div>
  </div>
  <%= f.input :recipe_id, as: :hidden, input_html: { data: { scheduler_target: "recipeInput" } } %>
  <%= f.submit "Create Schedule", class: "btn btn-cYellow w-100" %>
<% end %>

app/views/schedules/_search.html.erb
<div id="schedulerrecipe" class="row">
  <% if recipes.any? %>
    <div class="d-flex pt-2" style="overflow-y:auto;" data-scheduler-target="divRecipeCards">
      <% recipes.each do |recipe| %>
        <div class="text-cWhite mb-1 mt-2 p-2">
          <div class="card-recipe flex-column position-relative px-2 scheduler-recipe"
            data-action="click->scheduler#selectRecipe"
            data-id="<%= recipe.id %>">
            <% if recipe.photo.attached? %>
              <%= cl_image_tag recipe.photo.key,
              aspect_ratio: "1.0",
              crop: "fill", class: "card-image rounded-circle" %>
            <% else %>
              <img
              data-commons-image
              data-name="<%= j recipe.name %>"
              alt="<%= h recipe.name %>"
              loading="lazy"
              class="card-image rounded-circle">
              <% end %>
              <div class="text-cwhite text-center fs-6">
                <p class="my-1"><%= recipe.name %></p>
              </div>
              <span class="duration-font">
                <i class="fa-regular fa-clock"></i>
                <%= recipe.duration %> min
              </span>
              <div class="fs-6 favorite-style">
                <% if recipe.favorited_by?(current_user) %>
                  <i class="fa-solid fa-bookmark fa-lg mb-2"></i>
                <% end %>
              </div>
              <% if recipe.get_likes.size > 0 %>
                <div class="like-style fs-6">
                  <i class="fa-solid fa-heart fa-lg"></i>
                  <span class="badge text-cWhite p-0"><%= recipe.get_likes.size %></span>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <em class="text-cWhite">Sorry, no recipes found.</em>
    <% end %>
  </div>

app/views/schedules/create.turbo_stream.erb
<%= turbo_stream.replace "divForm" do %>
  <div id="divForm">
    <%= render "schedules/form", schedule: Schedule.new %>
  </div>
<% end %>
<%= turbo_stream.update "calendar" do %>
  <%= render "schedules/calendar", schedules: @schedules %>
<% end %>

app/views/schedules/generate_ai.turbo_stream.erb
<%= turbo_stream.replace "divFormAi" do %>
  <%= render "schedules/ai", schedule: Schedule.new, start_date: @start_date %>
<% end %>
<%= turbo_stream.update "calendar" do %>
  <%= render "schedules/calendar", schedules: @schedules %>
<% end %>

app/views/schedules/index.html.erb
<%= turbo_stream_from "schedules" %>
<div class="container" data-controller="scheduler">
  <h2 class="text-cWhite mt-5 mb-4">Your Meal Plan</h2>
  <%= link_to "Add to Meal Plan", "#",
    class: "btn btn-cDarkYellow mb-3 rounded-4",
    data: { bs_toggle: "collapse", bs_target: "#collapseExample" } %>
  <div class="text-cWhite collapse bg-cGray p-2 rounded-4" id="collapseExample"  >
    <ul class="nav nav-underline mb-3" id="schedulerNav" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link text-cWhite active"
          id="nav-ai-tab" data-bs-toggle="tab"
          data-bs-target="#nav-ai" type="button"
          role="tab" aria-controls="nav-ai"
          aria-selected="true">
          AI
        </button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link text-cWhite"
          id="nav-manually-tab" data-bs-toggle="tab"
          data-bs-target="#nav-manually" type="button"
          role="tab" aria-controls="nav-manually"
          aria-selected="false">
          Manually
        </button>
      </li>
    </ul>
    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="nav-ai" role="tabpanel" aria-labelledby="nav-ai-tab">
        <div id="divFormAi">
          <%= render "schedules/ai", schedule: @schedule %>
        </div>
      </div>
      <div class="tab-pane fade" id="nav-manually" role="tabpanel" aria-labelledby="nav-manually-tab">
        <div id="divForm">
          <%= render "schedules/form", schedule: @schedule %>
        </div>
      </div>
    </div>
  </div>
  <div class="text-cWhite collapse bg-cGray p-2 rounded-4" id="collapseAI">
  </div>
  <div class="mt-4">
    <div class="d-flex justify-content-between align-items-center">
      <%= link_to schedules_path(start_date: @start_date - 1.month), class: "btn rounded-circle text-cWhite" do %>
        <i class="fa-solid fa-arrow-left"></i>
      <% end %>
      <span class="text-cWhite d-flex align-items-center"><%= @start_date.strftime("%B %Y") %></span>
      <%= link_to schedules_path(start_date: @start_date + 1.month), class: "btn rounded-circle text-cWhite" do %>
        <i class="fa-solid fa-arrow-right"></i>
      <% end %>
    </div>
    <div id="calendar" class="mt-3" style="overflow-x:auto;max-width:400px">
      <%= render "schedules/calendar", schedules: @schedules %>
    </div>
  </div>
  <div class="p-3 w-100 h-25" data-scheduler-target="eventList">
  </div>
</div>

app/views/schedules/index.turbo_stream.erb
<%= turbo_stream.update "schedulerrecipe" do %>
  <%= render "schedules/search", recipes: @recipes %>
<% end %>

app/views/schedules/show.turbo_stream.erb
<%= turbo_stream.update "schedulerrecipe" do %>
  <%= render "schedules/search", recipes: @recipes %>
<% end %>